<?php
/*
| -------------------------------------------------------------------------
| KeyForum
| Copyright: © 2004 - 2005 KeyForum Team
| Web:       http://www.keyforum.net/
| Licence:   GPL v2.0
| -------------------------------------------------------------------------
| Modulo:     Elenco Emoticons
| Scritto da: Oberon
| -------------------------------------------------------------------------
*/

$emoticons = array(
  ":mellow:" => "mellow.gif",
  ":huh:" => "huh.gif",
  "^_^" => "happy.gif",
  ":o" => "ohmy.gif",
  ";)" => "wink.gif",
  ":P" => "tongue.gif",
  ":D" => "biggrin.gif",
  ":lol:" => "laugh.gif",
  "B)" => "cool.gif",
  ":rolleyes:" => "rolleyes.gif",
  "-_-" => "sleep.gif",
  "&lt;_&lt;" => "dry.gif",
  ":)" => "smile.gif",
  ":wub:" => "wub.gif",
  ":angry:" => "mad.gif",
  ":(" => "sad.gif",
  ":unsure:" => "unsure.gif",
  ":wacko:" => "wacko.gif",
  ":blink:" => "blink.gif",
  ":ph34r:" => "ph34r.gif",
  ":ambulance:" => "ambulance.gif",
  ":angel:" => "angel.gif",
  ":applause:" => "applause.gif",
  ":artist:" => "artist.gif",
  ":baby:" => "baby.gif",
  ":bag:" => "bag.gif",
  ":band:" => "band.gif",
  ":banned:" => "banned.gif",
  ":beer:" => "beer.gif",
  ":beer2:" => "beer2.gif",
  ":blowup:" => "blowup.gif",
  ":boat:" => "boat.gif",
  ":book:" => "book.gif",
  ":bow:" => "bow.gif",
  ":boxe:" => "boxe.gif",
  ":boxing:" => "boxing.gif",
  ":canadian:" => "canadian.gif",
  ":censored:" => "censored.gif",
  ":chair:" => "chair.gif",
  ":chef:" => "chef.gif",
  ":cool2:" => "cool2.gif",
  ":cowboy:" => "cowboy.gif",
  ":crutch:" => "crutch.gif",
  ":cry:" => "cry.gif",
  ":death:" => "death.gif",
  ":devil:" => "devil.gif",
  ":dj:" => "dj.gif",
  ":drunk:" => "drunk.gif",
  ":eat:" => "eat.gif",
  ":farewell:" => "farewell.gif",
  ":gathering:" => "gathering.gif",
  ":ghost:" => "ghost.gif",
  ":gossip:" => "gossip.gif",
  ":graduate:" => "graduate.gif",
  ":guillotine:" => "guillotine.gif",
  ":guitar:" => "guitar.gif",
  ":gunbandana:" => "gunbandana.gif",
  ":hammerer:" => "hammerer.gif",
  ":happybday:" => "happybday.gif",
  ":help:" => "help.gif",
  ":hmm:" => "hmm.gif",
  ":hoover:" => "hoover.gif",
  ":horse:" => "horse.gif",
  ":king:" => "king.gif",
  ":kiss:" => "kiss.gif",
  ":kiss2:" => "kiss2.gif",
  ":laughing:" => "laughing.gif",
  ":love:" => "love.gif",
  ":mad2:" => "mad2.gif",
  ":mobile:" => "mobile.gif",
  ":nono:" => "nono.gif",
  ":nugget:" => "nugget.gif",
  ":phone:" => "phone.gif",
  ":photo:" => "photo.gif",
  ":pizza:" => "pizza.gif",
  ":punk:" => "punk.gif",
  ":ranting:" => "ranting.gif",
  ":rotfl:" => "rotfl.gif",
  ":runaway:" => "runaway.gif",
  ":sbav:" => "sbav.gif",
  ":sbav2:" => "sbav2.gif",
  ":scared:" => "scared.gif",
  ":scooter:" => "scooter.gif",
  ":secret:" => "secret.gif",
  ":serenade:" => "serenade.gif",
  ":shifty:" => "shifty.gif",
  ":shock:" => "shock.gif",
  ":sign-ban:" => "sign-ban.gif",
  ":sign-dots:" => "sign-dots.gif",
  ":sign-offtopic:" => "sign-offtopic.gif",
  ":sign-spam:" => "sign-spam.gif",
  ":sign-stupid:" => "sign-stupid.gif",
  ":sleeping:" => "sleeping.gif",
  ":starwars:" => "starwars.gif",
  ":surrender:" => "surrender.gif",
  ":terafin-grin:" => "terafin-grin.gif",
  ":thumbdown:" => "thumbdown.gif",
  ":thumbup:" => "thumbup.gif",
  ":tomato:" => "tomato.gif",
  ":tongue2:" => "tongue2.gif",
  ":tooth:" => "tooth.gif",
  ":tv:" => "tv.gif",
  ":uh:" => "uh.gif",
  ":wallbash:" => "wallbash.gif",
  ":whistling:" => "whistling.gif",
  ":wine:" => "wine.gif",
  ":worthy:" => "worthy.gif",
  ":wub2:" => "wub2.gif",
  ":xmas:" => "xmas.gif",
  ":yeahright:" => "yeahright.gif",
  ":yes:" => "yes.gif",
);

?>